-- MySQL Script generated by MySQL Workbench
-- Sun Jun 26 16:53:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredient` (
  `id` varchar(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Taco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`taco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`taco` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Taco_Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`taco_ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`taco_ingredients` (
  `taco_id` BIGINT NOT NULL,
  `ingredients_id` varchar(45) NOT NULL,
  INDEX `taco_idx` (`taco_id` ASC) VISIBLE,
  INDEX `ingredient_idx` (`ingredients_id` ASC) VISIBLE,
  CONSTRAINT `FK_taco_to_taco_ingr`
    FOREIGN KEY (`taco_id`)
    REFERENCES `mydb`.`Taco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ingr_to_taco_ingr`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `mydb`.`ingredient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Taco_Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` BIGINT NOT NULL auto_increment,
  `user_id` bigint not null,
  `placed_at` TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_user_to_order`
      FOREIGN KEY (`user_id`)
          REFERENCES `mydb`.`user` (`id`)
          ON delete CASCADE
          ON UPDATE CASCADE )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Taco_Order_Tacos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_tacos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_tacos` (
  `order_id` BIGINT NOT NULL,
  `tacos_id` BIGINT NOT NULL,
  INDEX `taco_idx` (`tacos_id` ASC) VISIBLE,
  INDEX `order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FK_taco_to_taco_order`
    FOREIGN KEY (`tacos_id`)
    REFERENCES `mydb`.`taco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_order_to_taco`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


DROP TABLE IF EXISTS `mydb`.`user` ;

create table IF NOT EXISTS `mydb`.`user`
(
    id           bigint auto_increment primary key,
    username     varchar(64)  not null,
    password     varchar(500) not null,
    fullname     varchar(64)  null,
    street       varchar(128) null,
    city         varchar(64)  null,
    state        varchar(64)  null,
    zip          varchar(64)  null,
    phone_number varchar(64)  null,
    constraint user_username_uindex
        unique (username)
)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`role`;

CREATE TABLE IF NOT EXISTS `mydb`.`role`
(
    id bigint primary key not null auto_increment,
    name varchar(32) not null unique
)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`user_role`;

CREATE TABLE IF NOT EXISTS `mydb`.`user_role`
(
    user_id bigint not null,
    role_id bigint not null,
    CONSTRAINT `FK_user_to_user_role`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `FK_role_to_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
